version: '3'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      FASTAPI_ENV: development
    volumes:
      - .:/app
    working_dir: /app

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    environment:
      FASTAPI_ENV: test
      PYTHONPATH: /app